on:
  issue_comment:
    types:
      - created

jobs:
  pr-comment:
    if: ${{ github.event.issue.pull_request || github.event.issue-comment}}
    runs-on: ubuntu-latest
    steps:
      - run: echo "This was a comment on a pull request"