name: test and deploy
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJs
        uses: actions/setup-node@v3
      - name: install dependencies
        run: npm ci
      - name: Run Tests
        run: npm test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJs
        uses: actions/setup-node@v3
      - name: install dependencies
        run: npm ci
      - name: build project
        run: npm run build
      - name: Deploy
        run: echo "deploying..."
  test_workflow_command:
    runs-on: ubuntu-latest
    steps:
      - name: debug-commadn
        run: |
          echo "hello world"
          echo "::debug::setting debug message"